// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: create_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users
(name, username, password, social_id, email, profile_image, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, name, created_at, updated_at, email, profile_image, username, password, social_id
`

type CreateUserParams struct {
	Name         string      `json:"name"`
	Username     string      `json:"username"`
	Password     string      `json:"password"`
	SocialID     pgtype.Text `json:"social_id"`
	Email        string      `json:"email"`
	ProfileImage pgtype.Text `json:"profile_image"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Password,
		arg.SocialID,
		arg.Email,
		arg.ProfileImage,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ProfileImage,
		&i.Username,
		&i.Password,
		&i.SocialID,
	)
	return i, err
}
