// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: create_noti.sql

package sqlc

import (
	"context"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO "notifications"
(
    body, data, title, token, created_at, updated_at
)
VALUES ($1, $2, $3, $4, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, title, body, data, token, created_at, updated_at
`

type CreateNotificationParams struct {
	Body  string `json:"body"`
	Data  []byte `json:"data"`
	Title string `json:"title"`
	Token string `json:"token"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.Body,
		arg.Data,
		arg.Title,
		arg.Token,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Body,
		&i.Data,
		&i.Token,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
