// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: delete_event.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteEventByID = `-- name: DeleteEventByID :execresult
DELETE FROM "events" WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteEventByID(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteEventByID, id)
}
