// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: delete_user.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgconn"
)

const deleteUser = `-- name: DeleteUser :execresult
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (pgconn.CommandTag, error) {
	return q.db.Exec(ctx, deleteUser, id)
}
