// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: delete_user.sql

package sqlc

import (
	"context"
)

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users WHERE id = $1
    RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int32, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}
