// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: find_user_by_username.sql

package sqlc

import (
	"context"
)

const findUserByUsername = `-- name: FindUserByUsername :one
SELECT id, name, created_at, updated_at, email, profile_image, username, password, social_id, token FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) FindUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ProfileImage,
		&i.Username,
		&i.Password,
		&i.SocialID,
		&i.Token,
	)
	return i, err
}
