// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: find_tag_by_token.sql

package sqlc

import (
	"context"
)

const findTagNameByTokens = `-- name: FindTagNameByTokens :many
SELECT tag
FROM "follow_by_tag"
WHERE user_token = $1
`

func (q *Queries) FindTagNameByTokens(ctx context.Context, userToken string) ([]string, error) {
	rows, err := q.db.Query(ctx, findTagNameByTokens, userToken)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var tag string
		if err := rows.Scan(&tag); err != nil {
			return nil, err
		}
		items = append(items, tag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
