// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: find_user_by_social_id.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const findUserBySocialId = `-- name: FindUserBySocialId :one
SELECT id, name, created_at, updated_at, email, profile_image, username, password, social_id, token FROM users
WHERE social_id = $1 LIMIT 1
`

func (q *Queries) FindUserBySocialId(ctx context.Context, socialID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserBySocialId, socialID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ProfileImage,
		&i.Username,
		&i.Password,
		&i.SocialID,
		&i.Token,
	)
	return i, err
}
