// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: find_user_by_email.sql

package sqlc

import (
	"context"
)

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, name, role, created_at, updated_at, email, profile_image, username, password, social_id FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ProfileImage,
		&i.Username,
		&i.Password,
		&i.SocialID,
	)
	return i, err
}
