// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: find_token_by_tagname.sql

package sqlc

import (
	"context"
)

const findTokensByTagName = `-- name: FindTokensByTagName :many
SELECT user_token
FROM "follow_by_tag"
WHERE tag = $1
`

func (q *Queries) FindTokensByTagName(ctx context.Context, tag string) ([]string, error) {
	rows, err := q.db.Query(ctx, findTokensByTagName, tag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_token string
		if err := rows.Scan(&user_token); err != nil {
			return nil, err
		}
		items = append(items, user_token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
