// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: find_user_by_id.sql

package sqlc

import (
	"context"
)

const findUserByID = `-- name: FindUserByID :one
SELECT id, name, role, created_at, updated_at, email, profile_image, username, password, social_id FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) FindUserByID(ctx context.Context, id int32) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Role,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Email,
		&i.ProfileImage,
		&i.Username,
		&i.Password,
		&i.SocialID,
	)
	return i, err
}
