// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: follow_tag.sql

package sqlc

import (
	"context"
)

const followTag = `-- name: FollowTag :one
INSERT INTO "follow_by_tag"
(
    tag, user_token, created_at, updated_at
)
VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
    RETURNING id, tag, user_token, created_at, updated_at
`

type FollowTagParams struct {
	Tag       string `json:"tag"`
	UserToken string `json:"user_token"`
}

func (q *Queries) FollowTag(ctx context.Context, arg FollowTagParams) (FollowByTag, error) {
	row := q.db.QueryRow(ctx, followTag, arg.Tag, arg.UserToken)
	var i FollowByTag
	err := row.Scan(
		&i.ID,
		&i.Tag,
		&i.UserToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
