// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: follow_event.sql

package sqlc

import (
	"context"
)

const followEvent = `-- name: FollowEvent :one
INSERT INTO "following_events"
(
    event_id, user_id, created_at, updated_at
)
VALUES ($1, $2, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
RETURNING id, event_id, user_id, created_at, updated_at
`

type FollowEventParams struct {
	EventID int32 `json:"event_id"`
	UserID  int32 `json:"user_id"`
}

func (q *Queries) FollowEvent(ctx context.Context, arg FollowEventParams) (FollowingEvent, error) {
	row := q.db.QueryRow(ctx, followEvent, arg.EventID, arg.UserID)
	var i FollowingEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
