// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Event struct {
	ID           int32            `json:"id"`
	StartDate    pgtype.Timestamp `json:"start_date"`
	EndDate      pgtype.Timestamp `json:"end_date"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
	Title        string           `json:"title"`
	Latitude     float64          `json:"latitude"`
	Longitude    float64          `json:"longitude"`
	Price        float64          `json:"price"`
	Rating       float64          `json:"rating"`
	Image        string           `json:"image"`
	Creator      string           `json:"creator"`
	Detail       string           `json:"detail"`
	LocationName string           `json:"location_name"`
	NeedRegis    bool             `json:"need_regis"`
}

type Tag struct {
	ID         int32            `json:"id"`
	Color      string           `json:"color"`
	Name       string           `json:"name"`
	Category   string           `json:"category"`
	IsOfficial bool             `json:"is_official"`
	CreatedAt  pgtype.Timestamp `json:"created_at"`
	UpdatedAt  pgtype.Timestamp `json:"updated_at"`
}

type User struct {
	ID        int32            `json:"id"`
	Name      string           `json:"name"`
	Role      string           `json:"role"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
