// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0
// source: update_event_noti.sql

package sqlc

import (
	"context"
)

const updateEventNoti = `-- name: UpdateEventNoti :one
UPDATE events SET
                  need_noti = false,
                  updated_at = CURRENT_TIMESTAMP


WHERE id = $1
    RETURNING id, start_date, end_date, created_at, updated_at, title, latitude, longitude, price, image, detail, location_name, need_regis, tag, creator, regis_amount, regis_max, need_noti
`

func (q *Queries) UpdateEventNoti(ctx context.Context, id int32) (Event, error) {
	row := q.db.QueryRow(ctx, updateEventNoti, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Latitude,
		&i.Longitude,
		&i.Price,
		&i.Image,
		&i.Detail,
		&i.LocationName,
		&i.NeedRegis,
		&i.Tag,
		&i.Creator,
		&i.RegisAmount,
		&i.RegisMax,
		&i.NeedNoti,
	)
	return i, err
}
